//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class AGENDA : XPLiteObject
    {
        int fNUM_RENDEZVOUS;
        [Key]
        public int NUM_RENDEZVOUS
        {
            get { return fNUM_RENDEZVOUS; }
            set { SetPropertyValue<int>("NUM_RENDEZVOUS", ref fNUM_RENDEZVOUS, value); }
        }
        string fMESSAGE;
        [Size(SizeAttribute.Unlimited)]
        public string MESSAGE
        {
            get { return fMESSAGE; }
            set { SetPropertyValue<string>("MESSAGE", ref fMESSAGE, value); }
        }
        DateTime fDAT_RENDEZVOUS;
        public DateTime DAT_RENDEZVOUS
        {
            get { return fDAT_RENDEZVOUS; }
            set { SetPropertyValue<DateTime>("DAT_RENDEZVOUS", ref fDAT_RENDEZVOUS, value); }
        }
        DateTime fDEBUTDate;
        public DateTime DEBUTDate
        {
            get { return fDEBUTDate; }
            set { SetPropertyValue<DateTime>("DEBUTDate", ref fDEBUTDate, value); }
        }
        DateTime fFINDate;
        public DateTime FINDate
        {
            get { return fFINDate; }
            set { SetPropertyValue<DateTime>("FINDate", ref fFINDate, value); }
        }
        bool fVALIDE;
        public bool VALIDE
        {
            get { return fVALIDE; }
            set { SetPropertyValue<bool>("VALIDE", ref fVALIDE, value); }
        }
    }

}
