//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class Autre_reglement : XPLiteObject
    {
        string fCode_Autre_reg;
        [Key]
        [Size(50)]
        public string Code_Autre_reg
        {
            get { return fCode_Autre_reg; }
            set { SetPropertyValue<string>("Code_Autre_reg", ref fCode_Autre_reg, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        decimal fPrix;
        public decimal Prix
        {
            get { return fPrix; }
            set { SetPropertyValue<decimal>("Prix", ref fPrix, value); }
        }
        Kadhiya fCode_Kadhiya;
        [Size(50)]
        [Association(@"Autre_reglementReferencesKadhiya")]
        public Kadhiya Code_Kadhiya
        {
            get { return fCode_Kadhiya; }
            set { SetPropertyValue<Kadhiya>("Code_Kadhiya", ref fCode_Kadhiya, value); }
        }
    }

}
