//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class AVOCAT_CONTRE : XPLiteObject
    {
        string fCOD_AVOCAT;
        [Key]
        [Size(50)]
        public string COD_AVOCAT
        {
            get { return fCOD_AVOCAT; }
            set { SetPropertyValue<string>("COD_AVOCAT", ref fCOD_AVOCAT, value); }
        }
        string fNom;
        public string Nom
        {
            get { return fNom; }
            set { SetPropertyValue<string>("Nom", ref fNom, value); }
        }
        string fCtitre;
        public string Ctitre
        {
            get { return fCtitre; }
            set { SetPropertyValue<string>("Ctitre", ref fCtitre, value); }
        }
        string fTel;
        [Size(50)]
        public string Tel
        {
            get { return fTel; }
            set { SetPropertyValue<string>("Tel", ref fTel, value); }
        }
        string fGsm;
        [Size(50)]
        public string Gsm
        {
            get { return fGsm; }
            set { SetPropertyValue<string>("Gsm", ref fGsm, value); }
        }
        string fAdresse;
        [Size(SizeAttribute.Unlimited)]
        public string Adresse
        {
            get { return fAdresse; }
            set { SetPropertyValue<string>("Adresse", ref fAdresse, value); }
        }
        string fFax;
        [Size(50)]
        public string Fax
        {
            get { return fFax; }
            set { SetPropertyValue<string>("Fax", ref fFax, value); }
        }
        string fCin;
        [Size(50)]
        public string Cin
        {
            get { return fCin; }
            set { SetPropertyValue<string>("Cin", ref fCin, value); }
        }
        string fLieu_cin;
        public string Lieu_cin
        {
            get { return fLieu_cin; }
            set { SetPropertyValue<string>("Lieu_cin", ref fLieu_cin, value); }
        }
        DateTime fDate_cin;
        public DateTime Date_cin
        {
            get { return fDate_cin; }
            set { SetPropertyValue<DateTime>("Date_cin", ref fDate_cin, value); }
        }
        string fVille;
        public string Ville
        {
            get { return fVille; }
            set { SetPropertyValue<string>("Ville", ref fVille, value); }
        }
        string fCP;
        [Size(50)]
        public string CP
        {
            get { return fCP; }
            set { SetPropertyValue<string>("CP", ref fCP, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fEmail;
        [Size(50)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        string fCode_ka;
        [Size(50)]
        public string Code_ka
        {
            get { return fCode_ka; }
            set { SetPropertyValue<string>("Code_ka", ref fCode_ka, value); }
        }
        [Association(@"kadhiya_avocatReferencesAVOCAT_CONTRE", typeof(kadhiya_avocat))]
        public XPCollection<kadhiya_avocat> kadhiya_avocats { get { return GetCollection<kadhiya_avocat>("kadhiya_avocats"); } }
    }

}
