//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class ClientContre_Kadhiya : XPLiteObject
    {
        int fCode_clcon_ka;
        [Key(true)]
        public int Code_clcon_ka
        {
            get { return fCode_clcon_ka; }
            set { SetPropertyValue<int>("Code_clcon_ka", ref fCode_clcon_ka, value); }
        }
        Kadhiya fCode_kadhiya;
        [Size(50)]
        [Association(@"ClientContre_KadhiyaReferencesKadhiya")]
        public Kadhiya Code_kadhiya
        {
            get { return fCode_kadhiya; }
            set { SetPropertyValue<Kadhiya>("Code_kadhiya", ref fCode_kadhiya, value); }
        }
        Client_Contre fCode_Cl;
        [Size(50)]
        [Association(@"ClientContre_KadhiyaReferencesClient_Contre")]
        public Client_Contre Code_Cl
        {
            get { return fCode_Cl; }
            set { SetPropertyValue<Client_Contre>("Code_Cl", ref fCode_Cl, value); }
        }
    }

}
