//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class Conseil_Juridique : XPLiteObject
    {
        string fCode_Conseil;
        [Key]
        [Size(50)]
        public string Code_Conseil
        {
            get { return fCode_Conseil; }
            set { SetPropertyValue<string>("Code_Conseil", ref fCode_Conseil, value); }
        }
        string fClient;
        [Size(50)]
        public string Client
        {
            get { return fClient; }
            set { SetPropertyValue<string>("Client", ref fClient, value); }
        }
        string fCode_kadhiya;
        [Size(50)]
        public string Code_kadhiya
        {
            get { return fCode_kadhiya; }
            set { SetPropertyValue<string>("Code_kadhiya", ref fCode_kadhiya, value); }
        }
        string fNom;
        [Size(50)]
        public string Nom
        {
            get { return fNom; }
            set { SetPropertyValue<string>("Nom", ref fNom, value); }
        }
        string fType_Conseil;
        [Size(50)]
        public string Type_Conseil
        {
            get { return fType_Conseil; }
            set { SetPropertyValue<string>("Type_Conseil", ref fType_Conseil, value); }
        }
        string fSujet;
        [Size(SizeAttribute.Unlimited)]
        public string Sujet
        {
            get { return fSujet; }
            set { SetPropertyValue<string>("Sujet", ref fSujet, value); }
        }
        string fNom_client;
        [Size(50)]
        public string Nom_client
        {
            get { return fNom_client; }
            set { SetPropertyValue<string>("Nom_client", ref fNom_client, value); }
        }
        string fNom_kadhiya;
        [Size(50)]
        public string Nom_kadhiya
        {
            get { return fNom_kadhiya; }
            set { SetPropertyValue<string>("Nom_kadhiya", ref fNom_kadhiya, value); }
        }
        DateTime fDate_Conseil;
        public DateTime Date_Conseil
        {
            get { return fDate_Conseil; }
            set { SetPropertyValue<DateTime>("Date_Conseil", ref fDate_Conseil, value); }
        }
        decimal fPrix;
        public decimal Prix
        {
            get { return fPrix; }
            set { SetPropertyValue<decimal>("Prix", ref fPrix, value); }
        }
        DateTime fDate_prix;
        public DateTime Date_prix
        {
            get { return fDate_prix; }
            set { SetPropertyValue<DateTime>("Date_prix", ref fDate_prix, value); }
        }
        DateTime fDate_fin_kadhiya;
        public DateTime Date_fin_kadhiya
        {
            get { return fDate_fin_kadhiya; }
            set { SetPropertyValue<DateTime>("Date_fin_kadhiya", ref fDate_fin_kadhiya, value); }
        }
        DateTime fDate_fin_rapport;
        public DateTime Date_fin_rapport
        {
            get { return fDate_fin_rapport; }
            set { SetPropertyValue<DateTime>("Date_fin_rapport", ref fDate_fin_rapport, value); }
        }
        DateTime fDate_fin_frais;
        public DateTime Date_fin_frais
        {
            get { return fDate_fin_frais; }
            set { SetPropertyValue<DateTime>("Date_fin_frais", ref fDate_fin_frais, value); }
        }
        string fetat_reglement;
        [Size(50)]
        public string etat_reglement
        {
            get { return fetat_reglement; }
            set { SetPropertyValue<string>("etat_reglement", ref fetat_reglement, value); }
        }
        decimal fmontant_restant;
        public decimal montant_restant
        {
            get { return fmontant_restant; }
            set { SetPropertyValue<decimal>("montant_restant", ref fmontant_restant, value); }
        }
        string fNum_dossier;
        [Size(50)]
        public string Num_dossier
        {
            get { return fNum_dossier; }
            set { SetPropertyValue<string>("Num_dossier", ref fNum_dossier, value); }
        }
        string fNom_dossier;
        public string Nom_dossier
        {
            get { return fNom_dossier; }
            set { SetPropertyValue<string>("Nom_dossier", ref fNom_dossier, value); }
        }
    }

}
