//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class Contrat : XPLiteObject
    {
        string fCode_Contra;
        [Key]
        [Size(50)]
        public string Code_Contra
        {
            get { return fCode_Contra; }
            set { SetPropertyValue<string>("Code_Contra", ref fCode_Contra, value); }
        }
        Client fCode_Client;
        [Size(50)]
        [Association(@"ContratReferencesClient")]
        public Client Code_Client
        {
            get { return fCode_Client; }
            set { SetPropertyValue<Client>("Code_Client", ref fCode_Client, value); }
        }
        string fNum_docier;
        [Size(50)]
        public string Num_docier
        {
            get { return fNum_docier; }
            set { SetPropertyValue<string>("Num_docier", ref fNum_docier, value); }
        }
        string fPlace;
        [Size(50)]
        public string Place
        {
            get { return fPlace; }
            set { SetPropertyValue<string>("Place", ref fPlace, value); }
        }
        Client_Contre fCode_Client_Con;
        [Size(50)]
        [Association(@"ContratReferencesClient_Contre")]
        public Client_Contre Code_Client_Con
        {
            get { return fCode_Client_Con; }
            set { SetPropertyValue<Client_Contre>("Code_Client_Con", ref fCode_Client_Con, value); }
        }
        string fNom;
        public string Nom
        {
            get { return fNom; }
            set { SetPropertyValue<string>("Nom", ref fNom, value); }
        }
        string fNature;
        public string Nature
        {
            get { return fNature; }
            set { SetPropertyValue<string>("Nature", ref fNature, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
    }

}
