//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class DOCUMENT1 : XPLiteObject
    {
        decimal fCOD_DOC;
        [Key]
        public decimal COD_DOC
        {
            get { return fCOD_DOC; }
            set { SetPropertyValue<decimal>("COD_DOC", ref fCOD_DOC, value); }
        }
        byte[] fFICHIER1;
        [Size(SizeAttribute.Unlimited)]
        public byte[] FICHIER1
        {
            get { return fFICHIER1; }
            set { SetPropertyValue<byte[]>("FICHIER1", ref fFICHIER1, value); }
        }
        string fNOM_FICHIER1;
        [Size(SizeAttribute.Unlimited)]
        public string NOM_FICHIER1
        {
            get { return fNOM_FICHIER1; }
            set { SetPropertyValue<string>("NOM_FICHIER1", ref fNOM_FICHIER1, value); }
        }
        decimal fCOD_OP;
        public decimal COD_OP
        {
            get { return fCOD_OP; }
            set { SetPropertyValue<decimal>("COD_OP", ref fCOD_OP, value); }
        }
        string fcategorie;
        [Size(50)]
        public string categorie
        {
            get { return fcategorie; }
            set { SetPropertyValue<string>("categorie", ref fcategorie, value); }
        }
        Kadhiya fcode_kadeya;
        [Size(50)]
        [Association(@"DOCUMENT1ReferencesKadhiya")]
        public Kadhiya code_kadeya
        {
            get { return fcode_kadeya; }
            set { SetPropertyValue<Kadhiya>("code_kadeya", ref fcode_kadeya, value); }
        }
    }

}
