//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class Document_ka : XPLiteObject
    {
        int fCode_doc;
        [Key(true)]
        public int Code_doc
        {
            get { return fCode_doc; }
            set { SetPropertyValue<int>("Code_doc", ref fCode_doc, value); }
        }
        string fNom;
        [Size(SizeAttribute.Unlimited)]
        public string Nom
        {
            get { return fNom; }
            set { SetPropertyValue<string>("Nom", ref fNom, value); }
        }
        string fType;
        public string Type
        {
            get { return fType; }
            set { SetPropertyValue<string>("Type", ref fType, value); }
        }
        string fDocum;
        public string Docum
        {
            get { return fDocum; }
            set { SetPropertyValue<string>("Docum", ref fDocum, value); }
        }
        string fCode_kadhiya;
        public string Code_kadhiya
        {
            get { return fCode_kadhiya; }
            set { SetPropertyValue<string>("Code_kadhiya", ref fCode_kadhiya, value); }
        }
    }

}
