//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class FormeJuridique : XPLiteObject
    {
        int fCodeFormeJuridique;
        [Key]
        public int CodeFormeJuridique
        {
            get { return fCodeFormeJuridique; }
            set { SetPropertyValue<int>("CodeFormeJuridique", ref fCodeFormeJuridique, value); }
        }
        string fFormeJuridique1;
        [Size(50)]
        [Persistent(@"FormeJuridique")]
        public string FormeJuridique1
        {
            get { return fFormeJuridique1; }
            set { SetPropertyValue<string>("FormeJuridique1", ref fFormeJuridique1, value); }
        }
    }

}
