//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class Jalsa : XPLiteObject
    {
        string fCode_Jalsa;
        [Key]
        [Size(50)]
        public string Code_Jalsa
        {
            get { return fCode_Jalsa; }
            set { SetPropertyValue<string>("Code_Jalsa", ref fCode_Jalsa, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }
        DateTime fDate_Prochaine;
        public DateTime Date_Prochaine
        {
            get { return fDate_Prochaine; }
            set { SetPropertyValue<DateTime>("Date_Prochaine", ref fDate_Prochaine, value); }
        }
        string fCOD_PALAIS;
        [Size(50)]
        public string COD_PALAIS
        {
            get { return fCOD_PALAIS; }
            set { SetPropertyValue<string>("COD_PALAIS", ref fCOD_PALAIS, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fhokom;
        [Size(SizeAttribute.Unlimited)]
        public string hokom
        {
            get { return fhokom; }
            set { SetPropertyValue<string>("hokom", ref fhokom, value); }
        }
        Kadhiya fCode_ka;
        [Size(50)]
        [Association(@"JalsaReferencesKadhiya")]
        public Kadhiya Code_ka
        {
            get { return fCode_ka; }
            set { SetPropertyValue<Kadhiya>("Code_ka", ref fCode_ka, value); }
        }
        [Association(@"Document_JalsaReferencesJalsa", typeof(Document_Jalsa))]
        public XPCollection<Document_Jalsa> Document_Jalsas { get { return GetCollection<Document_Jalsa>("Document_Jalsas"); } }
    }

}
