//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class Kadhiya : XPLiteObject
    {
        string fCode_kadhiya;
        [Key]
        [Size(50)]
        public string Code_kadhiya
        {
            get { return fCode_kadhiya; }
            set { SetPropertyValue<string>("Code_kadhiya", ref fCode_kadhiya, value); }
        }
        string fNum_dossier;
        [Size(50)]
        public string Num_dossier
        {
            get { return fNum_dossier; }
            set { SetPropertyValue<string>("Num_dossier", ref fNum_dossier, value); }
        }
        string fEmplacement;
        [Size(SizeAttribute.Unlimited)]
        public string Emplacement
        {
            get { return fEmplacement; }
            set { SetPropertyValue<string>("Emplacement", ref fEmplacement, value); }
        }
        string fClient;
        [Size(50)]
        public string Client
        {
            get { return fClient; }
            set { SetPropertyValue<string>("Client", ref fClient, value); }
        }
        string fClient_Contre;
        [Size(50)]
        public string Client_Contre
        {
            get { return fClient_Contre; }
            set { SetPropertyValue<string>("Client_Contre", ref fClient_Contre, value); }
        }
        string fSujet;
        [Size(SizeAttribute.Unlimited)]
        public string Sujet
        {
            get { return fSujet; }
            set { SetPropertyValue<string>("Sujet", ref fSujet, value); }
        }
        string fType_ka;
        [Size(50)]
        public string Type_ka
        {
            get { return fType_ka; }
            set { SetPropertyValue<string>("Type_ka", ref fType_ka, value); }
        }
        string fObservation;
        [Size(SizeAttribute.Unlimited)]
        public string Observation
        {
            get { return fObservation; }
            set { SetPropertyValue<string>("Observation", ref fObservation, value); }
        }
        DateTime fDate_Debut;
        public DateTime Date_Debut
        {
            get { return fDate_Debut; }
            set { SetPropertyValue<DateTime>("Date_Debut", ref fDate_Debut, value); }
        }
        DateTime fDate_Fin;
        public DateTime Date_Fin
        {
            get { return fDate_Fin; }
            set { SetPropertyValue<DateTime>("Date_Fin", ref fDate_Fin, value); }
        }
        decimal fPrix;
        public decimal Prix
        {
            get { return fPrix; }
            set { SetPropertyValue<decimal>("Prix", ref fPrix, value); }
        }
        string fNom_dossier;
        public string Nom_dossier
        {
            get { return fNom_dossier; }
            set { SetPropertyValue<string>("Nom_dossier", ref fNom_dossier, value); }
        }
        string fNom;
        public string Nom
        {
            get { return fNom; }
            set { SetPropertyValue<string>("Nom", ref fNom, value); }
        }
        string fetat_reglement;
        [Size(50)]
        public string etat_reglement
        {
            get { return fetat_reglement; }
            set { SetPropertyValue<string>("etat_reglement", ref fetat_reglement, value); }
        }
        decimal fmontant_restant;
        public decimal montant_restant
        {
            get { return fmontant_restant; }
            set { SetPropertyValue<decimal>("montant_restant", ref fmontant_restant, value); }
        }
        DateTime fDate_prix;
        public DateTime Date_prix
        {
            get { return fDate_prix; }
            set { SetPropertyValue<DateTime>("Date_prix", ref fDate_prix, value); }
        }
        DateTime fDate_fin_kadhiya;
        public DateTime Date_fin_kadhiya
        {
            get { return fDate_fin_kadhiya; }
            set { SetPropertyValue<DateTime>("Date_fin_kadhiya", ref fDate_fin_kadhiya, value); }
        }
        DateTime fDate_fin_rapport;
        public DateTime Date_fin_rapport
        {
            get { return fDate_fin_rapport; }
            set { SetPropertyValue<DateTime>("Date_fin_rapport", ref fDate_fin_rapport, value); }
        }
        DateTime fDate_fin_frais;
        public DateTime Date_fin_frais
        {
            get { return fDate_fin_frais; }
            set { SetPropertyValue<DateTime>("Date_fin_frais", ref fDate_fin_frais, value); }
        }
        bool fradioButton1;
        public bool radioButton1
        {
            get { return fradioButton1; }
            set { SetPropertyValue<bool>("radioButton1", ref fradioButton1, value); }
        }
        bool fradioButton2;
        public bool radioButton2
        {
            get { return fradioButton2; }
            set { SetPropertyValue<bool>("radioButton2", ref fradioButton2, value); }
        }
        bool fradioButton3;
        public bool radioButton3
        {
            get { return fradioButton3; }
            set { SetPropertyValue<bool>("radioButton3", ref fradioButton3, value); }
        }
        bool fradioButton4;
        public bool radioButton4
        {
            get { return fradioButton4; }
            set { SetPropertyValue<bool>("radioButton4", ref fradioButton4, value); }
        }
        string fnum_archive;
        public string num_archive
        {
            get { return fnum_archive; }
            set { SetPropertyValue<string>("num_archive", ref fnum_archive, value); }
        }
        string ftawr;
        public string tawr
        {
            get { return ftawr; }
            set { SetPropertyValue<string>("tawr", ref ftawr, value); }
        }
        string femplacement_doss;
        [Size(SizeAttribute.Unlimited)]
        public string emplacement_doss
        {
            get { return femplacement_doss; }
            set { SetPropertyValue<string>("emplacement_doss", ref femplacement_doss, value); }
        }
        string fhokom;
        public string hokom
        {
            get { return fhokom; }
            set { SetPropertyValue<string>("hokom", ref fhokom, value); }
        }
        decimal ffrais_juridique;
        public decimal frais_juridique
        {
            get { return ffrais_juridique; }
            set { SetPropertyValue<decimal>("frais_juridique", ref ffrais_juridique, value); }
        }
        decimal ffrais_divers;
        public decimal frais_divers
        {
            get { return ffrais_divers; }
            set { SetPropertyValue<decimal>("frais_divers", ref ffrais_divers, value); }
        }
        decimal fsomme;
        public decimal somme
        {
            get { return fsomme; }
            set { SetPropertyValue<decimal>("somme", ref fsomme, value); }
        }
        string ftype_payement;
        public string type_payement
        {
            get { return ftype_payement; }
            set { SetPropertyValue<string>("type_payement", ref ftype_payement, value); }
        }
        string fmethode_payement;
        public string methode_payement
        {
            get { return fmethode_payement; }
            set { SetPropertyValue<string>("methode_payement", ref fmethode_payement, value); }
        }
        [Association(@"Autre_reglementReferencesKadhiya", typeof(Autre_reglement))]
        public XPCollection<Autre_reglement> Autre_reglements { get { return GetCollection<Autre_reglement>("Autre_reglements"); } }
        [Association(@"ClientContre_KadhiyaReferencesKadhiya", typeof(ClientContre_Kadhiya))]
        public XPCollection<ClientContre_Kadhiya> ClientContre_Kadhiyas { get { return GetCollection<ClientContre_Kadhiya>("ClientContre_Kadhiyas"); } }
        [Association(@"JalsaReferencesKadhiya", typeof(Jalsa))]
        public XPCollection<Jalsa> Jalsas { get { return GetCollection<Jalsa>("Jalsas"); } }
        [Association(@"kadhiya_avocatReferencesKadhiya", typeof(kadhiya_avocat))]
        public XPCollection<kadhiya_avocat> kadhiya_avocats { get { return GetCollection<kadhiya_avocat>("kadhiya_avocats"); } }
        [Association(@"Kadhiya_JusticeReferencesKadhiya", typeof(Kadhiya_Justice))]
        public XPCollection<Kadhiya_Justice> Kadhiya_Justices { get { return GetCollection<Kadhiya_Justice>("Kadhiya_Justices"); } }
        [Association(@"Reglement_ClientReferencesKadhiya", typeof(Reglement_Client))]
        public XPCollection<Reglement_Client> Reglement_Clients { get { return GetCollection<Reglement_Client>("Reglement_Clients"); } }
        [Association(@"Client_ContreReferencesKadhiya", typeof(Client_Contre))]
        public XPCollection<Client_Contre> Client_Contres { get { return GetCollection<Client_Contre>("Client_Contres"); } }
    }

}
