//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class Kadhiya_Justice : XPLiteObject
    {
        int fCode_jus_ka;
        [Key(true)]
        public int Code_jus_ka
        {
            get { return fCode_jus_ka; }
            set { SetPropertyValue<int>("Code_jus_ka", ref fCode_jus_ka, value); }
        }
        Justice_Port fCOD_Justice;
        [Size(50)]
        [Association(@"Kadhiya_JusticeReferencesJustice_Port")]
        public Justice_Port COD_Justice
        {
            get { return fCOD_Justice; }
            set { SetPropertyValue<Justice_Port>("COD_Justice", ref fCOD_Justice, value); }
        }
        Kadhiya fCode_Kadhiya;
        [Size(50)]
        [Association(@"Kadhiya_JusticeReferencesKadhiya")]
        public Kadhiya Code_Kadhiya
        {
            get { return fCode_Kadhiya; }
            set { SetPropertyValue<Kadhiya>("Code_Kadhiya", ref fCode_Kadhiya, value); }
        }
        decimal fPrix;
        public decimal Prix
        {
            get { return fPrix; }
            set { SetPropertyValue<decimal>("Prix", ref fPrix, value); }
        }
        [Association(@"Reglement_JusticeReferencesKadhiya_Justice", typeof(Reglement_Justice))]
        public XPCollection<Reglement_Justice> Reglement_Justices { get { return GetCollection<Reglement_Justice>("Reglement_Justices"); } }
    }

}
