//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class kadhiya_avocat : XPLiteObject
    {
        int fCode_Av_ka;
        [Key(true)]
        public int Code_Av_ka
        {
            get { return fCode_Av_ka; }
            set { SetPropertyValue<int>("Code_Av_ka", ref fCode_Av_ka, value); }
        }
        Kadhiya fCode_Kadiya;
        [Size(50)]
        [Association(@"kadhiya_avocatReferencesKadhiya")]
        public Kadhiya Code_Kadiya
        {
            get { return fCode_Kadiya; }
            set { SetPropertyValue<Kadhiya>("Code_Kadiya", ref fCode_Kadiya, value); }
        }
        AVOCAT_CONTRE fCode_Avocat;
        [Size(50)]
        [Association(@"kadhiya_avocatReferencesAVOCAT_CONTRE")]
        public AVOCAT_CONTRE Code_Avocat
        {
            get { return fCode_Avocat; }
            set { SetPropertyValue<AVOCAT_CONTRE>("Code_Avocat", ref fCode_Avocat, value); }
        }
        decimal fPrix;
        public decimal Prix
        {
            get { return fPrix; }
            set { SetPropertyValue<decimal>("Prix", ref fPrix, value); }
        }
        [Association(@"Reglement_AvocatReferenceskadhiya_avocat", typeof(Reglement_Avocat))]
        public XPCollection<Reglement_Avocat> Reglement_Avocats { get { return GetCollection<Reglement_Avocat>("Reglement_Avocats"); } }
    }

}
