//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class PALAIS_JUSTICE : XPLiteObject
    {
        string fCOD_PALAIS;
        [Key]
        [Size(50)]
        public string COD_PALAIS
        {
            get { return fCOD_PALAIS; }
            set { SetPropertyValue<string>("COD_PALAIS", ref fCOD_PALAIS, value); }
        }
        string fNom;
        [Size(200)]
        public string Nom
        {
            get { return fNom; }
            set { SetPropertyValue<string>("Nom", ref fNom, value); }
        }
        string fCtitre;
        public string Ctitre
        {
            get { return fCtitre; }
            set { SetPropertyValue<string>("Ctitre", ref fCtitre, value); }
        }
        string fTel;
        public string Tel
        {
            get { return fTel; }
            set { SetPropertyValue<string>("Tel", ref fTel, value); }
        }
        string fAdresse;
        [Size(SizeAttribute.Unlimited)]
        public string Adresse
        {
            get { return fAdresse; }
            set { SetPropertyValue<string>("Adresse", ref fAdresse, value); }
        }
        string fFax;
        public string Fax
        {
            get { return fFax; }
            set { SetPropertyValue<string>("Fax", ref fFax, value); }
        }
        string fVille;
        public string Ville
        {
            get { return fVille; }
            set { SetPropertyValue<string>("Ville", ref fVille, value); }
        }
        string fCP;
        [Size(50)]
        public string CP
        {
            get { return fCP; }
            set { SetPropertyValue<string>("CP", ref fCP, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fEmail;
        [Size(50)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
    }

}
