//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class Reglement_Avocat : XPLiteObject
    {
        int fCode_Reg_Avc;
        [Key(true)]
        public int Code_Reg_Avc
        {
            get { return fCode_Reg_Avc; }
            set { SetPropertyValue<int>("Code_Reg_Avc", ref fCode_Reg_Avc, value); }
        }
        kadhiya_avocat fCode_kadhiya;
        [Association(@"Reglement_AvocatReferenceskadhiya_avocat")]
        public kadhiya_avocat Code_kadhiya
        {
            get { return fCode_kadhiya; }
            set { SetPropertyValue<kadhiya_avocat>("Code_kadhiya", ref fCode_kadhiya, value); }
        }
        decimal fMontant_reg;
        public decimal Montant_reg
        {
            get { return fMontant_reg; }
            set { SetPropertyValue<decimal>("Montant_reg", ref fMontant_reg, value); }
        }
        string fMode_Payement;
        public string Mode_Payement
        {
            get { return fMode_Payement; }
            set { SetPropertyValue<string>("Mode_Payement", ref fMode_Payement, value); }
        }
        string fNum_piece;
        [Size(50)]
        public string Num_piece
        {
            get { return fNum_piece; }
            set { SetPropertyValue<string>("Num_piece", ref fNum_piece, value); }
        }
        string fBanque;
        public string Banque
        {
            get { return fBanque; }
            set { SetPropertyValue<string>("Banque", ref fBanque, value); }
        }
        DateTime fDate_payement;
        public DateTime Date_payement
        {
            get { return fDate_payement; }
            set { SetPropertyValue<DateTime>("Date_payement", ref fDate_payement, value); }
        }
        string fClient;
        [Size(50)]
        public string Client
        {
            get { return fClient; }
            set { SetPropertyValue<string>("Client", ref fClient, value); }
        }
        decimal fMontant_paye;
        public decimal Montant_paye
        {
            get { return fMontant_paye; }
            set { SetPropertyValue<decimal>("Montant_paye", ref fMontant_paye, value); }
        }
        DateTime fDate_piece;
        public DateTime Date_piece
        {
            get { return fDate_piece; }
            set { SetPropertyValue<DateTime>("Date_piece", ref fDate_piece, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
    }

}
