//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class Type_Mise_en_œuvre : XPLiteObject
    {
        string fNum;
        [Key]
        [Size(50)]
        public string Num
        {
            get { return fNum; }
            set { SetPropertyValue<string>("Num", ref fNum, value); }
        }
        string fNom;
        [Size(SizeAttribute.Unlimited)]
        public string Nom
        {
            get { return fNom; }
            set { SetPropertyValue<string>("Nom", ref fNom, value); }
        }
    }

}
