//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace avocat2015.DATA.baavocat
{

    public partial class Ville : XPLiteObject
    {
        int fCodeVille;
        [Key]
        public int CodeVille
        {
            get { return fCodeVille; }
            set { SetPropertyValue<int>("CodeVille", ref fCodeVille, value); }
        }
        string fNomVille;
        [Size(50)]
        public string NomVille
        {
            get { return fNomVille; }
            set { SetPropertyValue<string>("NomVille", ref fNomVille, value); }
        }
    }

}
